server:
  port: 8080
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
  forward-headers-strategy: native
  error:
    whitelabel:
      enabled: false

spring:
  cache:
    type: redis
  datasource:
    username: root
    password: '!Whu123456'
    url: jdbc:mysql://localhost:3306/flingo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  #redis


#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.example.unisys.entity

#showSql
logging:
  pattern:
    console:
package:
  model: com.uvt.flingo.entity
  dao: com.uvt.flingo.dao
  xml: mapping

